import './globals.scss'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

export const metadata: Metadata = {
	title: 'Balloons',
	description: 'Generated by create next app',
}

const roboto = Roboto({
	weight: ['100', '400', '500', '700'],
	subsets: ['cyrillic', 'latin'],
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='ru'>
			<body className={roboto.className}>{children}</body>
		</html>
	)
}
